dist: trusty
sudo: false
language: node_js
node_js:
  - "6"

cache:
  directories:
    - node_modules
os:
  - linux

before_install:
  # Use a virtual display.
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # Install latest chrome.
  - export CHROME_BIN=chromium-browser
  - npm install -g npm@5.0.4

install:
  - npm install

script:
  - npm run lint
  - npm run test
  - npm run integration