name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Install dependencies
        run: yarn install

      - name: Run lint
        run: yarn lint

      - name: Run tests
        run: yarn test:ci

      - name: Build
        run: yarn build:demo
